#ifndef CA_BUNDLE_RTDB_H
#define CA_BUNDLE_RTDB_H

const char *CA_BUNDLE_RTDB = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIFYzCCBEugAwIBAgIRALtb3DA0mzoTDcmE1QaqZMEwDQYJKoZIhvcNAQELBQAw\n" \
"OzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczEM\n" \
"MAoGA1UEAxMDV1IxMB4XDTI1MDUxMjIxNTM0M1oXDTI1MDgxMDIxNTM0MlowLTEr\n" \
"MCkGA1UEAwwiKi51cy1jZW50cmFsMS5maXJlYmFzZWRhdGFiYXNlLmFwcDCCASIw\n" \
"DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOrLT5VKYPtHlCAmgLcyrvRbeWmE\n" \
"Y/k+bCmZZSHYa0SPkl7A+tyPKm6X3SB/Oi1CzDOl34ZsyIxNK54LR1r030T2AkZo\n" \
"LW48uJXVEvAX0tXbXp0sN+qn4OBRdA6fqo/K47mlYuXgnQEUxk5nvlD0Un8eruyh\n" \
"uAa3Jah20RMxANVbMjMNY93TqonxFVpuvReuttWbHSLfuFpg+xpUjaRa8wwh4Zu1\n" \
"bmLl8Sx5g5MaCSUkvkqyBVF5Rb/rrtP+KPOGmQEAZvY1CLsIUF7Dfp8p+AIS5HxS\n" \
"Y7XhNTi78JzCBcBw1g/OlLrfLf/U05Q2fBjqd5kdpyaNyyyDXVFw0PAVLA0CAwEA\n" \
"AaOCAm4wggJqMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAM\n" \
"BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQuQXhMpP+8mDHx5k2vqohu3WiXCjAfBgNV\n" \
"HSMEGDAWgBRmaUnU3iqckQPPiQ4kuA4wA26ILjBeBggrBgEFBQcBAQRSMFAwJwYI\n" \
"KwYBBQUHMAGGG2h0dHA6Ly9vLnBraS5nb29nL3Mvd3IxL3UxczAlBggrBgEFBQcw\n" \
"AoYZaHR0cDovL2kucGtpLmdvb2cvd3IxLmNydDA/BgNVHREEODA2giIqLnVzLWNl\n" \
"bnRyYWwxLmZpcmViYXNlZGF0YWJhc2UuYXBwghAqLmZpcmViYXNlaW8uY29tMBMG\n" \
"A1UdIAQMMAowCAYGZ4EMAQIBMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jLnBr\n" \
"aS5nb29nL3dyMS82bXlHTElWeW5jZy5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHz\n" \
"APEAdwDM+w9qhXEJZf6Vm1PO6bJ8IumFXA2XjbapflTA/kwNsAAAAZbGtD//AAAE\n" \
"AwBIMEYCIQDZhV+rW6XXqtOUO+N8rMAv+JPktUPDiRmfEuiD3pASUwIhAK33EEfe\n" \
"XmqsfP/vwnPBXXcZgGBEhbTcB873kmvwgM8IAHYAEvFONL1TckyEBhnDjz96E/jn\n" \
"tWKHiJxtMAWE6+WGJjoAAAGWxrQ/ygAABAMARzBFAiEA/+QF8DA5/uBu2nVHD2S0\n" \
"hCWkpwmpBNruMEyJiPUX+usCIA5JbnFPRqH1kBI1wXmDVVIBSeMVlxh1B8NWcf83\n" \
"Kqb0MA0GCSqGSIb3DQEBCwUAA4IBAQCxbSVTSzrKVko+mX4AS5U/Riom867H5l46\n" \
"6dureMsjbP7qOFWSjckJnrd1X6c69zAq0KjitV7B80kAZyTS7nGi3wkJZQL379PV\n" \
"4yeyje5V4HD2EavjeqkPR5rfzD3rwKyjUCAYJQN8K58dTLmcOS1e08HwBEsYsM2s\n" \
"JX79B6mBmFuUzdFqNdIOoD367a1DHqTKUfdOOdOnFFI+uEcQmQwsvLszIHpZL+P/\n" \
"Yyph5x+ndvTDpPlHdH92grmR9/k+U9GxJ/dRofXKFlMUDdxWOIBA2deN/66XGhbm\n" \
"1zSKVbOU22uQaM8uVgkQXBKrXiAFytGbgpK+yNuAwssj1FYppCwc\n" \
"-----END CERTIFICATE-----\n";

#endif

